server:
  port: 9097
  servlet:
    context-path: /
spring:
  application:
    name: demo
  datasource:
    name: iris
    url: jdbc:IRIS://127.0.0.1:51775/ML
    username: _system
    password: jiahemk

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.intersystems.jdbc.IRISDriver




mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.demo.entity


